# Generated by Django 5.2.6 on 2026-02-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_card_generated',
            field=models.BooleanField(default=False),
        ),
    ]
