# Generated by Django 5.2.6 on 2026-04-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notice_expiry_date_notice_is_pinned'),
        ('student', '0004_alter_student_roll_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-enrollment_date']},
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
