# Generated by Django 5.2.6 on 2026-04-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_options_alter_student_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id_card_generated',
        ),
    ]
