# Generated by Django 5.2.6 on 2026-04-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_student_id_card_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
