# Generated by Django 5.2.6 on 2026-04-09 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_topic_notes_topic_notes_file'),
        ('student', '0007_student_fees_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('topic', 'student', 'date')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='lecture_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical')], default='theory', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
