# Generated by Django 5.2.6 on 2026-04-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_result_percentage_result_total_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
