# Generated by Django 5.2.6 on 2026-05-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_certificate_marks_certificate_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fees_status',
        ),
        migrations.AddField(
            model_name='student',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
