# Generated by Django 5.2.6 on 2025-09-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_studentanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_answer',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1),
        ),
    ]
