# Generated by Django 5.2.6 on 2026-04-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notice_expiry_date_notice_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
