# Generated by Django 5.2.6 on 2026-04-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_topic_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='notes',
        ),
        migrations.AddField(
            model_name='topic',
            name='notes_file',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
