# Generated by Django 5.2.6 on 2026-04-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_topic_notes_topic_notes_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_topics',
            field=models.IntegerField(default=0),
        ),
    ]
